/*
 * Created on 3 avr. 2014 ( Time 19:43:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.validator;

import org.demo.bean.Book ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity Book
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookValidator extends AbstractValidator<Book>{

    @Override
    public void validateEntity(Book entity, Errors errors) {
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "id", MessagesKeys.ID_MUST_DEFINE);

		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "publisherId", MessagesKeys.NOT_BLANK);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "authorId", MessagesKeys.NOT_BLANK);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "isbn", MessagesKeys.NOT_BLANK);

    }
}