/*
 * Created on 3 avr. 2014 ( Time 19:43:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.validator;

import org.demo.bean.BookOrder ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity BookOrder
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookOrderValidator extends AbstractValidator<BookOrder>{

    @Override
    public void validateEntity(BookOrder entity, Errors errors) {
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "id", MessagesKeys.ID_MUST_DEFINE);

		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "shopCode", MessagesKeys.NOT_BLANK);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "customerCode", MessagesKeys.NOT_BLANK);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "employeeCode", MessagesKeys.NOT_BLANK);

    }
}