/*
 * Created on 3 avr. 2014 ( Time 19:43:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.validator;

import org.demo.bean.Customer ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity Customer
 * 
 * @author Telosys Tools Generator
 *
 */
public class CustomerValidator extends AbstractValidator<Customer>{

    @Override
    public void validateEntity(Customer entity, Errors errors) {
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "code", MessagesKeys.ID_MUST_DEFINE);

		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "countryCode", MessagesKeys.NOT_BLANK);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "login", MessagesKeys.NOT_BLANK);

    }
}