/*
 * Created on 3 avr. 2014 ( Time 19:43:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.validator;

import org.demo.bean.EmployeeGroup ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity EmployeeGroup
 * 
 * @author Telosys Tools Generator
 *
 */
public class EmployeeGroupValidator extends AbstractValidator<EmployeeGroup>{

    @Override
    public void validateEntity(EmployeeGroup entity, Errors errors) {
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "employeeCode", MessagesKeys.ID_MUST_DEFINE);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "groupId", MessagesKeys.ID_MUST_DEFINE);


    }
}