/*
 * Created on 3 avr. 2014 ( Time 19:43:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.validator;

import org.demo.bean.Publisher ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity Publisher
 * 
 * @author Telosys Tools Generator
 *
 */
public class PublisherValidator extends AbstractValidator<Publisher>{

    @Override
    public void validateEntity(Publisher entity, Errors errors) {
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "code", MessagesKeys.ID_MUST_DEFINE);

		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "countryCode", MessagesKeys.NOT_BLANK);

    }
}