/*
 * Created on 3 avr. 2014 ( Time 19:43:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.validator;

import org.demo.bean.Workgroup ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity Workgroup
 * 
 * @author Telosys Tools Generator
 *
 */
public class WorkgroupValidator extends AbstractValidator<Workgroup>{

    @Override
    public void validateEntity(Workgroup entity, Errors errors) {
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "id", MessagesKeys.ID_MUST_DEFINE);

		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "name", MessagesKeys.NOT_BLANK);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "description", MessagesKeys.NOT_BLANK);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "creationDate", MessagesKeys.NOT_BLANK);

    }
}