/*
 * Created on 3 avr. 2014 ( Time 19:43:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.BookOrderItem ;

import org.springframework.data.repository.CrudRepository;

import org.demo.bean.BookOrderItemKey ;
import org.demo.bean.BookOrder;
import org.demo.bean.Book;
import java.util.List;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RestResource;



/**
 * Spring JPA Repository for BookOrderItem
 * 
 * @author Telosys Tools Generator
 *
 */
public interface BookOrderItemRepository extends CrudRepository<BookOrderItem, BookOrderItemKey> {

	@RestResource(rel="byBookOrder", path="byBookOrder")
	public List<BookOrderItem> findByBookOrder (
			@Param("bookorder") BookOrder bookorder);

	@RestResource(rel="byBook", path="byBook")
	public List<BookOrderItem> findByBook (
			@Param("book") Book book);


}