/*
 * Created on 3 avr. 2014 ( Time 19:43:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.Country ;

import org.springframework.data.repository.CrudRepository;



/**
 * Spring JPA Repository for Country
 * 
 * @author Telosys Tools Generator
 *
 */
public interface CountryRepository extends CrudRepository<Country, String> {


}