/*
 * Created on 3 avr. 2014 ( Time 19:43:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.Synopsis ;

import org.springframework.data.repository.CrudRepository;

import org.demo.bean.Book;
import java.util.List;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RestResource;


/**
 * Spring JPA Repository for Synopsis
 * 
 * @author Telosys Tools Generator
 *
 */
public interface SynopsisRepository extends CrudRepository<Synopsis, Integer> {

	@RestResource(rel="byBook", path="byBook")
	public List<Synopsis> findByBook (
			@Param("book") Book book);


}